name: Deploy to Strato

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4

      # Optional für React/Vite/Vue:
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: 22
      # - run: npm ci
      # - run: npm run build

      - name: Dateien nach STRATO übertragen
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          source: "./*"
          target: "/konrep/"
